config/routes.rb
Bkb::Application.routes.draw do

  resources :user_sessions
  
  get 'login' => 'user_sessions#new', :as => :login
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  get 'search' => 'articles#search', :as => :search
  get 'articles/new' => 'articles#new', :as => :new_article
  get 'articles/:permalink/edit' => 'articles#edit', :as => :edit_article
  get 'articles/:permalink' => 'articles#show', :as => :show_article
  
  get 'articles/import' => 'articles#new_import', :as => :import_articles
  post 'articles/import' => 'articles#import'

  resources :articles
  
  root :to => 'articles#welcome'

end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Search
  include Mongoid::Timestamps

  field :title, type: String
  field :body, type: String
  field :permalink, type: String

  validates_presence_of :title, :body

  
  def save    
    self.permalink = self.title.to_slug
    super
    CrudLogger.log_operation(self.permalink, self.permalink, 'created')
  end
  
  def update_attributes(attributes = [])
    a = Article.find(self.id)
    old_permalink = ''
    
    if !a.nil?
      old_permalink = a.permalink
    end
    
    super(attributes)
    CrudLogger.log_operation(self.permalink, old_permalink, 'updated')
  end
  
  def destroy
    super    
    CrudLogger.log_operation(self.permalink, self.permalink, 'deleted')
  end
  
  search_in :title, :body

end

app/models/crud_logger.rb
class CrudLogger
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :permalink, type: String
  field :operation, type: String
  
  validates_inclusion_of :operation, allow_blank: false, in: ['created', 'updated', 'deleted'] 
  
  def self.log_operation(permalink, old_permalink, operation)
    log = CrudLogger.find_or_initialize_by(permalink: permalink)
    
    # the former permalink is to be deleted
    if permalink != old_permalink
      deletation_log = CrudLogger.find_or_initialize_by(permalink: old_permalink)
      deletation_log.operation = 'deleted'
      deletation_log.save
    end
    
    log.operation = operation
    log.save
  end
end

app/models/user.rb
class User
  include Mongoid::Document

  attr_accessible :email, :password, :password_confirmation
  
  authenticates_with_sorcery!
  
  validates_length_of :password, :minimum => 3, :message => "password must be at least 6 characters long", :if => :password
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :require_login, :except => [:not_authenticated]
    
  protected
  
  def not_authenticated
    redirect_to login_path, :alert => "Please, login first."
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_filter :require_login, :except => [:new, :edit, :create, :update, :destroy]

  def welcome

    @articles = [].each
    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @articles }
    end
  end
  
  def search
    respond_to do |format|
      format.html do
        @articles = Article.full_text_search(params[:q], match: :all).map do |article|
          article._keywords = []
          article.body = nil
          article
        end
        render 'index'
      end
      format.json do 
        @articles = Article.each
        render json: @articles 
      end
    end
  end

  def index
    respond_to do |format|
      format.html do
        @articles = Article.each.map do |article|
          article._keywords = []
          article.body = nil
          article
        end
      end
      format.json do 
        @articles = Article.each
        render json: @articles 
      end
    end
  end

  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  def edit
    @article = Article.find_by(permalink: params[:permalink])
  end

  def show
    @article = Article.find_by(permalink: params[:permalink])
    
    @article.body = "# " + @article.title + "\n" + @article.body
  end
  
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { 
          flash[:notice] = 'Article was successfully created.'
          redirect_to action: 'welcome'
        }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { 
          flash[:notice] = 'Article was successfully updated.'
          redirect_to action: 'welcome'
        }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { 
        flash[:notice] = 'Article was successfully deleted.'
        redirect_to action: 'welcome' 
      }
      format.json { head :no_content }
    end
  end

  def new_import

  end

  def import
    begin
      jsoned_articles = JSON.parse(params[:jsoned_articles])
    rescue
      respond_to do |format|
        format.html { 
          flash.now[:error] = 'Not valid Json'
          render action: "new_import" 
        }
      end
      return
    end

    valid_articles = [] 
    @invalid_articles = [] 

    jsoned_articles.each_with_index do |article, index|
      article = Article.new(article)

      if article.valid?
        valid_articles << article
      else
        article.instance_variable_set(:@index, index)
        @invalid_articles << article

      end
    end

    respond_to do |format|

      if @invalid_articles.empty?
        valid_articles.each do |article|
          article.save
        end

        format.html { 
          flash[:notice] = "#{valid_articles.count} article were successfully created."
          redirect_to action: 'welcome'
        }

      else
        format.html { render action: "new_import" }
      end
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, :except => [:destroy]
  
  def new
    @user = User.new
  end
  
  def create
    if @user = login(params[:user][:email], params[:user][:password], true)
      redirect_to root_path
    else
      @user = User.new
      flash.now[:error] = "Wrong email and password combination." 
      render :action => "new"
    end
  end
  
  def destroy
    logout
    flash[:notice] = "You have sucessfully logged out"
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper

end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div class="notifications">
      <% @article.errors.full_messages.each do |message| %>
        <div class=<%= "message-error" %>><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <div class="field form_article_title">
    <%= f.text_field :title, placeholder: 'Title', :class => 'form_article_title_input' %>
  </div>
  <div id="epiceditor", style="height: 400px;"></div>
  <%= f.text_area :body, placeholder: 'Write your article here. You can use markdown.', :id => 'epiceditor-textarea', :style => 'display: none;'%>
  
  
  <div class="actions">
    <%= f.submit 'Save', id: 'save-button' %>
  </div>
  
  
<% end %>


<script type="text/javascript">
//<![CDATA[
  start_epiceditor_edit_mode();

//]]>
</script>

app/views/articles/edit.html.erb
<%= render 'form' %>

<%= link_to 'Delete', @article, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/articles/index.html.erb
<div id='articles' >
</div>

<%= javascript_tag do %>
  <% @articles.each do |article| %>
    add_article(<%= article.to_json.html_safe %>, <%= "'#{show_article_path(:permalink => article.permalink)}'".html_safe %>, <%= logged_in? ? "'#{edit_article_path(:permalink => article.permalink)}'".html_safe : "null" %>);
  <% end %>
<% end %>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/new_import.erb
<%= form_tag action: "import", method: "post" do %>
  
  <% if @invalid_articles.present? and @invalid_articles.count > 0 %>
	  <% @invalid_articles.each do |article|%>
		<% if article.errors.any? %>
		  <div class="notifications">
			<% article.errors.full_messages.each do |message| %>
			  <div class=<%= "message-error" %>><%= "##{article.instance_variable_get(:@index)} - #{message}" %></div>
			<% end %>
		  </div>
		<% end %>
	  <% end %>
  <% end %>

  <div>
    <%= text_area_tag :jsoned_articles, nil, :placeholder => 'Json array with articles.', :class => "import_text_area" %>
  </div>
  <div>
    <%= submit_tag("Import") %>
  </div>
<% end %>

app/views/articles/show.erb
<div id="epiceditor"></div>
<%= text_area(:article, :body, :id => 'epiceditor-textarea', :style => 'display: none;') %>

<script type="text/javascript">
//<![CDATA[
  start_epiceditor_preview_mode();
//]]>
</script>

app/views/layouts/_navigation.html.erb
<div id="navigation">
  <%= form_tag("/search", method: "get") do %>
    <div class="navigation-search-box">
      <%= text_field_tag :q, nil, class: 'search-field' %>
      <%= submit_tag("Search") %>
    </div>
    
    <% if logged_in? %>
      <div class="navigation-option">
        <%= link_to 'Logout', logout_path, method: :delete %>
      </div>

      <div class="navigation-option">
        <%= link_to 'New', new_article_path %>
      </div>

      <div class="navigation-option">
        <%= link_to 'Import', import_articles_path %>
      </div>




    <% else %>

      <div class="navigation-option">
        <%= link_to 'Login', login_path %>
      </div>
    
    <% end %>

    <div class="navigation-option">
      <%= link_to 'List All', articles_path %>
    </div>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <title>Basic Knowledge Base</title>
  
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-47709257-1', 'basic-knowledge-base.herokuapp.com');
    ga('send', 'pageview');
  </script>
  
  </head>

  <body>

    <!-- Begin Wrapper -->
    <div id="wrapper">

      <!-- Begin Header -->
      <div id="header">
        Basic Knowledge Base
      </div>
      <!-- End Header -->

      <!-- Begin Naviagtion -->
      <%= render '/layouts/navigation' %>
      <!-- End Naviagtion -->

      <!-- Begin Content -->
      <div id="content">

        <% if flash.each.count > 0 %>
        <div class="notifications">
          <% flash.each do |type, message| %>
            <div class=<%= "message-#{type}" %>><%= message %></div>
          <% end %>
        </div>
        <% end %>

        <%= yield %>

      </div>
      <!-- End Content -->

    </div>
    <!-- End Wrapper -->

  </body>
</html>

app/views/user_sessions/new.html.erb
<%= form_for @user, :url => {:controller => 'user_sessions', :action => 'create'} do |f| %>
  
  <div class="login-form"> 
    <div> 
      <%= f.text_field :email, :placeholder => 'Email', :class => 'login-form-email-field' %>
    </div>
    
    <div>
      <%= f.password_field :password, :placeholder => 'Password', :class => 'login-form-password-field' %>
    </div>
    
    <div>
      <%= f.submit 'Login' %>
    </div>
  </div>

<% end %>